name: Build lazygit for Debian

on:
  workflow_dispatch:
    inputs:
      lazygit_version:
        description: The version of lazygit to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-lazygit:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout lazygit-debian
        uses: actions/checkout@v4

      - name: Build lazygit
        run: ./build.sh ${{ inputs.lazygit_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: lazygit_*.deb


  release-lazygit:
    name: (Draft-)Release lazygit for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-lazygit
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: lazygit_*.deb
          name: ${{ inputs.lazygit_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
